config/routes.rb
Rails.application.routes.draw do

  root "cocktails#index"

  resources "cocktails", only: [:show, :index, :new, :create] do
    resources "doses", only: [:new, :create]
  end

  delete "doses/:id", to: "doses#destroy", as: "delete_dose"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end

  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    id_for_redirect = @dose.cocktail_id
    @dose.destroy

    redirect_to cocktail_path(id_for_redirect)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<!-- add banner -->
<%= render "shared/banner" %>

<div class="container">
  <div class="row padded">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-6 col-md-2">

        <div class="card">
          <div class="card-category"><%= cocktail.name %> </div>
          <div class="card-description">
            <h2> Ingredients: </h2>
            <p>
              <% cocktail.ingredients.each_with_index do |ingredient, index| %>
                <% if index == 0 %>
                  <%= ingredient.name %>
                <% else %>
                 , <%= ingredient.name %>
                <% end %>
              <% end %>
            </p>
          </div>
          <%= link_to cocktail.name, cocktail_path(cocktail), class: "card-link" %>
        </div>

      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-2 col-xs-offset-5 padded">
      <%= link_to "Add Cocktail", new_cocktail_path, class: "navbar-wagon-button" %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
  <div class="col-xs-12 col-md-6 col-md-offset-3 padded">

      <%= simple_form_for(@cocktail) do |f| %>
      <%= f.error_notification %>

      <%= f.input :name %>

      <%= f.button :submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">

  <h1> <%= @cocktail[:name] %> </h1>
  <% @cocktail.doses.reverse.each_with_index do |dose, index| %>
  <p> <b> Step <%= index + 1 %></b>
  <p> <b> Ingredient: </b> <%= dose.ingredient.name %> </p>
  <p> <b> Instructions: </b> <%= dose.description %>
  <br>
  <%= link_to "Remove this step", delete_dose_path(dose), method: :delete %>
  <br>
  <% end %>
  <br>
  <%= link_to "Add a step", new_cocktail_dose_path(@cocktail) %>

</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3 padded">

      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.error_notification %>

      <%= f.input :description %>

      <%= f.association :ingredient %>

      <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>

<!--   add navbar  -->
<%= render "shared/navbar" %>

    <%= yield %>

<!--   add footer  -->

  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_url "banner-img.jpg" %>);">
  <div class="banner-content text-center">
    <h1>Ready to party?</h1>
    <h4>We have the best cocktails. No really. The very best. Nobody has cocktails like we do. Amazing!</h4>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag 'logo-img.jpg', class: "img-rounded" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-center hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
  </div>

  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to t(".top_call_to_action", default: "Add a cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>